name = "flare-peer"
main = "src/worker.js"
compatibility_date = "2024-07-22"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "<DATABASE_NAME>"
database_id = "<DATABASE_ID>"

[vars]
TURN_CUSTOM_DOMAIN = ""
TURN_KEY_API_TOKEN = "<TURN_KEY_API_TOKEN>"
TURN_KEY_ID = "<TURN_KEY_ID>"
